config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index'
   
   controller :sessions do
      get    'login'  => :new
      post   'login' => :create
      delete 'logout'=>:destroy
    end

scope '(:locale)' do
  resources :products
  resources :users
  resources :line_items
  resources :carts
  resources :orders
  get "store/index"

  root to: 'store#index', as: 'store'
  
  
  resources :products do
    get :who_bought, on: :member
  end
 end

end

app/views/layouts/application.html.erb
#encoding:UTF-8
<!DOCTYPE html>
<html>
<head>
  <title>在线商店</title>
  <%= stylesheet_link_tag 'scaffolds' %>
  <%= stylesheet_link_tag "store", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body id="store">
<div id="banner">
<%= form_tag store_path, class: 'locale' do %>
  <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s),
                               onchange: 'this.form.submit()' %>
  <%= submit_tag 'submit' %>
  <%= javascript_tag "$$('.locale input').each(Element.hide)" %>
<% end %>
  <%= image_tag("logo.png") %>
  <%= @page_title || t('.title') %>
  <p> 日期：<%= Time.now %> </p>
</div>
  <div id="columns">
    <div id="side">
    <div id="cart">
      <% if @cart %>
  <%= hidden_div_if(@cart.line_items.empty?, id: "cart") do %>
    <%= render @cart %>
    <% end %>
  <% end %>
    </div>
    <%= link_to t('.home'), store_path %><br />
    <a href="#"><%= t('.questions') %></a><br/>
    <a href="#"><%= t('.news') %></a><br/>
    <a href="#"><%= t('.contact') %></a><br/><br/>
   
   <% if session[:user_id] %>
   
    <%= link_to "订单", orders_path %><br />
    <%= link_to "产品", products_path %><br />
    <%= link_to "用户", users_path %><br/>
    <br />
    <%= button_to "退出", logout_path, method: :delete %>
   
    <% end %>
 
 </div>
  
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>